### ISSUE TITLE
View an agreement's audit trail/history

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1300]
### User Story
As an OPRE staff member, I want to view the history of changes and a record of the lifecycle of an agreement as part of other agreement details so that I can understand the full scope of all alterations to a contract.

### Acceptance Criteria
- [x] The user can view and see a list of all changes that occurred to a contract since its inception including the date of the change, what user made the change, and a succinct definition of what was altered.
- [x] The retention of the history should be exhaustive with no limit as to the age of a change
- [x] The history/list of all changes shouldn't be editable by regular users accessing the OPS interface
- [x] The list of items in the history should be sorted in descending order chronologically

-----------------------------------------

#### UX
- [x] Design already provided and discussed within #1156

##### Backend
- [x] #1361
  - [x] track team_members, support_contacts
  - [x] make history for BLIs, etc queryable by agreement ID
  - [x] fix issues with unwanted histories - BLIs, User getting history records with no changes with an Agreement is saved
- [ ] ~#1377~ saving for later 
- [x] agreement history endpoint that provides combined history of agreement with the history of it's BLIs, etc.
- [x] OpenAPI spec documentation

##### Frontend
- [x] #1385
- [x] Infinite scroll
- [x] simplify prepared changes https://github.com/HHS/OPRE-OPS/pull/1383#discussion_r1311727716

### Definition of Done Checklist
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] Build process updated
- [x] Documentation updated or added
- [x] Feature flags/toggles created

**Comment by kimschulke** [comment]
**Quotes from user research / feedback on agreement details design**
__* “Anytime there is an addition or subtraction, a notification would be good”_
_* “There's just all these, like responding to changes”_
_* “Seeing the changes in real time would be really helpful”_
_* “Right now I have to communicate the amount to project officers and then someone has to communicate it to the budget team to make the changes in MAPS but its nice to have that be a shared responsibility with CORS so they can do those changes themselves but I can still see what's happening”_
_* “somewhere I would want record if something gets edited…it would be good to have the amounts that changed from the original.”_
_* “The history and notes are great!”__

**What the need is…**
There are a lot of edits made to an agreement throughout the planning process and beyond, and it can be difficult to keep track of everything changing all the time. Users need to be able to quickly see what, specifically, has changed, when and by who. The reason why would be even more helpful.

**How our design meets this need…**
Our design includes a short/concise title that hi-lights in bold what specific change was made and when. This will make it easier for people to track specific changes, like when a BLI amount is edited, rather than seeing a generic update like “Agreement Edited” 

**Scenario example…**
If a user logs into OPS after a few weeks and notices SC1 looks different from what they remember last time.. they could go to the history and scroll through until they see “Budget Line Amount Edited.” Then they would stop scrolling and read the update. We believe this is an easier path than alternatively scanning for “Agreement Edited” and having to read each block of text until they find the one that says Budget Line SC1 amount changed.

**Comment by stevtek** [comment]
https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=6664-125775&mode=design&t=ewpjvnj7ljhtAJNL-4

**Comment by jonnalley** [comment]
1377 will be done separately/later and longer part of this.

**Comment by jonnalley** [comment]
9/28
