### ISSUE TITLE
Refactor `ops/util/auth.py` `is_authorized.__call__` function

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#1315]
The logic within this function needs some refactoring, as it was identified to be a bit complex, and not meeting the specific needs as intended. No specific use cases were identified, but walking through the logic proved it didn't meet the current need.

**Comment by xlorepdarkhelm** [comment]
The "is_authorized" was not working as we had originally intended, because the authorization gateway was expecting something that it didn't do. The AuthorizationGateway.is_authorized() method was expecting a list of permissions as the 2nd parameter. However, the @is_authorized() decorator was sending it only a single permission string. As such, it was being treated as a list, which would be a list of characters. And if any 1 of the characters in the list happened to be in the string containing all of the permissions, it would automatically say the person was authorized.

So: "DELETE_AGREEMENT" would then become ["D", "E", "L", "E", "T", "E", "_", "A", "G", "R", "E", "E", "M", "E", "N", "T"] and each letter would be checked. And if the string of permissions for the role was "{GET_AGREEMENT}", it would pass because "E" is in that string.

The solution was 2-fold. First, I split up the string of permissions for all of the user's roles into a set of strings, rather than just 1 long string. This is protection from part of the bug. The other part was I made AuthorizationGateway.is_authorized() work with the 2nd parameter being just 1 permission, not a list of permissions. Since the @is_authorized() decorator is the only thing calling that method, I feel confident I'm not breaking anything.
