### ISSUE TITLE
PoC: Switch to using Trussworks USWDS React Library

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#1604]
PoC to see if switching to the [Trussworks USWDS React library](https://github.com/trussworks/react-uswds/tree/main) is viable

### Acceptance Criteria
- [ ] _How will we know when this story is done?  List here the desired behavior that must be enabled for this story to be considered done_
- [ ] _Consider positive behavior (this user can do this thing in this situation)_
- [ ] _Consider negative behavior (this user should not be able to do this thing in this situation)_

-----------------------------------------

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [ ] Usability validated (UX team)
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_
* _Info already known or found, previous work that's been done?_

**Comment by stevtek** [comment]
I've experimented with Trussworks react-uswds and MetroStar's Comet.
I think Trussworks approach looks overly complicated and their tooltip may be unusable since it creates a button.  Comet uses USWDS modular's JavaScript rather then implementing their own like Trussworks and you could just use their code as an example to do your own.  Comet does have the same problem that I had doing my own with React.StrictMode causing double initialization of some components like character-count resulting in duplicate hint messages.

**Comment by fpigeonjr** [comment]
+1 for [Radix](https://www.radix-ui.com/) for a11y-focused unstyled component library

**Comment by jonnalley** [comment]
based on conversations I see here and in slack I'm tentatively closing but can re-open if it's premature
