### ISSUE TITLE
Verify if AWS DMS will work with source database version

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#192]
### Goals

Find out if AWS DMS will work with source database version our not. 

### Resources

[AWS DMS docs: Verifying that AWS DMS supports the source database version](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.Oracle.html#CHAP_Source.Oracle.Self-Managed.Configuration.DbVersion)

**Comment by amymok** [comment]
From [Using an Oracle database as a source for AWS DMS]:(https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.Oracle.html)
>AWS DMS supports the following Oracle database editions:
>- Oracle Enterprise Edition
>- Oracle Standard Edition
>- Oracle Express Edition
>- Oracle Personal Edition
>
>For self-managed Oracle databases, AWS DMS supports all Oracle database editions for versions 10.2 and later (for versions 10.x), 11g and up to 12.2, 18c, and 19c. **For Amazon RDS for Oracle databases that AWS manages, AWS DMS supports all Oracle database editions for versions 11g (versions 11.2.0.4 and later) and up to 12.2**, 18c, and 19c.

From the highlighted statement, I would assume that the vendor's Oracle database which is 12c Standard Edition Release 12.1.0.2.0, should be part of the support.

@alexsoble I tried the command in [AWS DMS docs: Verifying that AWS DMS supports the source database version](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.Oracle.html#CHAP_Source.Oracle.Self-Managed.Configuration.DbVersion).  I do get an error, but I think the reason is that the vendor did not give us privilege to read `v$parameter` table.  That needs to be granted explicitly.

I think we can continue to proceed based on the statement given above.  Unless we want to be extra safe to ask the vendor to grant us access to select from `v$parameter` so we can check if they have `name`, `value`, `description` columns.  I would think we do not need to.  Any concerns, thoughts @alexsoble @carjug?

**Comment by alexsoble** [comment]
@amymok Thanks for looking more into this and sharing these notes! If you feel comfortable proceeding based on the above, then I do too! Removing my review tag now. 👍 👍

**Comment by carjug** [comment]
+1 to what @alexsoble said!

**Comment by amymok** [comment]
Okay I am going to proceed with #183, and will close this card.
