### ISSUE TITLE
Log in is not succeeding

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#765]
## Expected Behavior
I expect that after clicking the sign in button from the main/front/landing page in OPS, that I go through login.gov to get signed in.

## Current Behavior
In the current dev environment (as deployed at 2151 ET on 03/17), log in is not successful. After providing credentials to login.gov, the user is redirected to OPS without being signed in.

## Steps to Reproduce
1. Navigate to [the dev front page](https://ops-dev.fr.cloud.gov)
2. Click the blue/white Sign-In button
3. Go through login.gov hoops to authenticate
4. Manually refresh the page to avoid bug #721 . 
5. Notice that the blue/white button in the upper-right corner still says sign "in" and the user's email address is not displayed.

## Context
I [deployed main as of 2151 on 03/17](https://github.com/HHS/OPRE-OPS/actions/runs/4453049339) to `development`. `staging` does not have this same issue and it was last [pushed/deployed to on 03/09](https://github.com/HHS/OPRE-OPS/actions/runs/4378556493).

**Comment by tdonaworth** [comment]
Main issue is an error in the user creation:

```
users.created_on does not exist
```

will need to look into this, and create additional tests to capture this scenario.

**Comment by tdonaworth** [comment]
Further investigation points to the `data-tools` not correctly updating tables after a schema change.  Will need to look into this.

**Comment by jonnalley** [comment]
still exists sadly...

**Comment by johndeange** [comment]
I experimented with deleting tables and generally putting the DB in a bad state and then restoring with `data-tools` and didn't have a problem, i.e. it always restored to a good state.  I suspect that the environment got into this bad state because the `data-tools task` itself didn't run or failed at deployment time.  The service provisioning has been intermittently failing due to timeouts - I made a change to increase the timeout for now.  Deploying the services via Docker container should fix the timeout issue (which is the current plan).
