### ISSUE TITLE
Filter for same-team agreements

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#803]
### User Story
As an OPRE staff member, I want to find a particular agreement out of the agreements I've been added as a team member or Lead on so I can take further action on that agreement.

### Acceptance Criteria
- [x] User can search or filter agreements that they have been added to as a team member
- [x] User can subsequently access the full details of a particular agreement they want to see more details of

-----------------------------------------

#### UX
- [x] Conduct research as needed
- [x] Explore design options
- [x] Share designs with stakeholders and other OPRE team members for feedback
- [x] Refine the design based on feedback
- [x] Provide design assets with annotations to developers

#### Dev

**DEV DISCUSS** - Do we want to pre-filter on the API, or filter on the frontend for the `Filtering`

***Backend***
- [x] #1030 @xlorepdarkhelm 
- [x] #1091 @xlorepdarkhelm 

***Frontend***
- [x] Update frontend components
  - [x] Create Table for listing Agreements
  - [x] #1215
  - [x] #1232
    - FIlter Types: reference Figma design, ❔ 
  - [x] Create component that displays the active filters as Tags
  - [x] #1295

### Definition of Done Checklist
- [x] UI works as designed (UX)
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- ~~[ ] Build process updated~~
- ~~[ ] Documentation updated or added~~
- ~~[ ] Feature flags/toggles created~~

### Additional Context & Resources
![image](https://github.com/HHS/OPRE-OPS/assets/56687505/8ec6b0b0-e7d7-4eac-8c3b-3ab2dbe87ead)

**Comment by kimschulke** [comment]
note to self: still need to design how the filter will work and what filter options will be included.

**Comment by johndeange** [comment]
Initial developer thoughts on Draft/Open/Closed:

```
Draft - has at least one BLI in Draft/In Review status
Active - all BLIs are in Planned+ status, but not in Closed list
Closed - all BLIs are in Obligated status (?)
```

**Comment by kimschulke** [comment]
Closed is not intended to equal Obligated. Closed would be after Obligated when it becomes past work and there is nothing left to do or spend.

**Comment by kimschulke** [comment]
For now, lets remove the "Closed" Tab as we still don't know how a "Closed" agreement will be defined and if it would even be a helpful category

**Comment by kimschulke** [comment]
**Design in Figma** - with edits from stakeholders feedback

https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=4128%3A113945&t=TK07LHXHwoW4lblI-1

**Comment by jonnalley** [comment]
agreement-level status now being scrubbed in favor of status at the BL-level only

**Comment by jonnalley** [comment]
@kimschulke @andressacurvelo might want to update the screenshot in this story this week after OPRE discussion to with one that omits the status column

**Comment by kimschulke** [comment]
Design in figma here: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=4720%3A145586&mode=design&t=O44DJkX0j1RPGZwE-1

**Comment by jonnalley** [comment]
@johndeange would you be willing to go through DoD and the AC and check off what you feel comfortable with ?

**Comment by kimschulke** [comment]
UX/UI Reveiew - a few things to note

- Per discussion with Andressa and John last week, we changed the filter defaults. Previously, in our original design, there were no pre-selected defaults and the user would have to choose what filters to apply. That has changed, and now the filters will default to all being pre-selected, and the user will have to choose which filters to remove. There were differing opinions on the this matter, but we decided to go with a majority vote on defaulting to all filters being pre-selected. This is something we should make sure we test with end users during our usability testing to make sure it is clear and easy to understand. Note we should start compiling a list of specific items we know we need to test at a later date.

- When testing the filters in Dev, I noticed the focus state on the radio buttons and dropdown components overlap with the component labels. We will need to adjust the spacing between labels and components to better accommodate the focus states. Unfortunately, the focus states are not included in the USWDS Figma Component Library we are using so they have not been accounted for in our designs. We will likely need to go back and check other components/focus states throughout OPS to see if this issue appears elsewhere - this would mean changing our spacing more globally rather than just in this specific instance.

Examples of the focus state overlapping with component labels:
<img width="356" alt="Screenshot 2023-08-11 at 11 57 46 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/75dc4978-3483-4b12-a18f-4a9a8ce4f532">

<img width="355" alt="Screenshot 2023-08-11 at 11 57 58 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/4d13f72d-c5d0-48db-adb4-159c79d3c99d">

What our USWDS component in Figma looks like (does not include focus state):
<img width="259" alt="Screenshot 2023-08-11 at 11 51 33 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/9950cf5f-d07d-44da-8372-8530c0a8c886">

**Comment by jonnalley** [comment]
@kimschulke @andressacurvelo those padding changes were made and merged into the `development` environment less than an hour ago so we should be all set now. You'll see them in `staging` tomorrow morning. That being said, I'll plan to move this story on to the next stage presuming all else is well.

**Comment by kimschulke** [comment]
Just checked dev and it looks good to me!

<img width="355" alt="Screenshot 2023-08-11 at 11 57 58 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/f3ce31f3-7476-4d05-9363-9978db2aa5b0">

<img width="356" alt="Screenshot 2023-08-11 at 11 57 46 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/fb1c1e53-c2d3-4f1c-8b7a-f31dea73ca45">
